[package]
name = "cargo-nixpackage"
version = "0.1.0"
edition = "2024"

[build]
targer = "./target"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4", features = [ 'derive' ] }
tera = "1.20.0"
